### ISSUE TITLE
Karma tests should be run against transpiled version of the code

### ISSUE THREAD

**Issue by nowtvicebergteam** [antonsamper/gulp-boilerplate#42]
Karma is currently being run against source code.

Which means if there is any ES6 compile error, concat error, etc.. karma will pass(against source code), which could potentially mean you are going to push broken code into production env.

**Comment by antonsamper** [comment]
when the tests run karma, the 'karma-babel-preprocessor' transpiles all the code anyway so this shouldnt be an issue
