### ISSUE TITLE
update tasks that contain sourcemaps to work more precisely 

### ISSUE THREAD

**Issue by nwc1991** [antonsamper/gulp-boilerplate#44]
`.pipe(plumber({errorHandler: sharedEvents.onError}))
    .pipe(gulpif(gulpOptions.env === 'dev', sourcemaps.init()))
    .pipe(babel())
    .pipe(gulpif(gulpOptions.env !== 'dev', uglify()))
    .pipe(concat('polyatomic.modules.bundle.js'))
    .pipe(gulpif(gulpOptions.env === 'dev', sourcemaps.write()))
    .pipe(gulp.dest(`${ sharedPaths.outputDir }/js`));`

**Comment by antonsamper** [comment]
This is happening when `concat` is used as merging all the files mangles the sourcemaps. As we are not concatenating the files during `dev`, this isnt an issue.
